version: '3.8'

services:
  meridian-power-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meridian-power-tracker
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - TZ=Pacific/Auckland
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
